modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/ITank/issues"

[[mods]]
modId="itank"
displayName="ITank"
version="${file.jarVersion}"
authors="Ewy"
credits="Does anyone actually reading the credits?"
description="Lightweight - Fancy looking - Liquid & fluid storage tank"

[[dependencies.itank]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.itank]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20]"
    ordering="NONE"
    side="BOTH"